apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: frontend
  newName: 194722430197.dkr.ecr.us-west-2.amazonaws.com/training/craftista_frontend
  newTag: latest
